### ISSUE TITLE
When first install , how to set default language to en-US?

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#1]
Hi Sir:

when i run  "php yii rbac/rbac/init" , "php yii users/user/create"... how to set default language is en-US?

**Comment by Dominus77** [comment]
https://github.com/Dominus77/yii2-advanced-start/blob/288682261f87af0a72a6abb2693d55d0076c8fe5/console/config/main.php#L11

**Comment by polinwei** [comment]
it is work. thanks.
