### ISSUE TITLE
folder: '/vendor/bower-asset/sweetalert2/dist' disappear

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#10]
I found out the folder: '/vendor/bower-asset/sweetalert2/dist' disappear, How can I get it back?

I got error message:
<pre>
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: Y:\xampp\htdocs\myweb/vendor/bower-asset/sweetalert2/dist
</pre>

**Comment by Dominus77** [comment]
Hi!
Check composer.json
[https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/composer.json#L39](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/composer.json#L39)
and
[https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/common/config/main.php#L6](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/common/config/main.php#L6)
Read
[https://github.com/Dominus77/yii2-sweetalert2-widget/issues/2](https://github.com/Dominus77/yii2-sweetalert2-widget/issues/2)

**Comment by Dominus77** [comment]
In this assembly, everything is set up and should work out of the box

**Comment by polinwei** [comment]
I do those steps as below , then It is back to normal. Thanks

```
1. Delete folder vendor
2. Delete file composer.lock
3. composer self-update
4. composer install
```
