### ISSUE TITLE
i18 in ActiveForm field does not work

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#11]
` $form->field($model, 'cellPhoneNo')->textInput(['class' => 'form-control']) `  the wording `cellPhoneNo` can not translate correct.

model code
<pre>
	public function attributeLabels()
	{
		return [
				'cellPhoneNo' => Module::t('module', 'cellPhoneNo'),
				'message' => Yii::t('app', 'Message'),
		];
	}
</pre>

**Comment by Dominus77** [comment]
Hi!
Check the module configuration
Using the users module as an example
1. [https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/Module.php#L67](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/Module.php#L67)

2. [https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/Bootstrap.php#L21](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/Bootstrap.php#L21)

3. Existence of folders
[https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/users/messages](https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/users/messages)

4. Connecting Bootstrap.php in the application configuration
[https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/frontend/config/main.php#L17](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/frontend/config/main.php#L17)

5. Connecting the module string
[https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/models/User.php#L12](https://github.com/Dominus77/yii2-advanced-start/blob/9b32ccbb57c3624e00c038609f845c10482fce33/modules/users/models/User.php#L12)

**Comment by polinwei** [comment]
Hi Sir:
I did all above steps. In the view: sendtext.php , only outside of  ActiveForm like Module::t('module', 'SendCHTMessage');  can work.

`View:`
![view](https://user-images.githubusercontent.com/7941129/31830512-0423da48-b5f3-11e7-8d00-964c6bdb4583.png)


`Bootstrap`
![bootstrap](https://user-images.githubusercontent.com/7941129/31828762-d6db4378-b5ed-11e7-9728-e603bc8b776f.png)

`config`
![config](https://user-images.githubusercontent.com/7941129/31828763-d705f848-b5ed-11e7-9d45-4e95de130a0f.png)
`
frontend`
![frontend](https://user-images.githubusercontent.com/7941129/31828764-d72ff7f6-b5ed-11e7-9cdd-797a6cf20891.png)

`model`
![model](https://user-images.githubusercontent.com/7941129/31828765-d75f281e-b5ed-11e7-8e17-36df1fec98f9.png)

`module`
![module](https://user-images.githubusercontent.com/7941129/31828766-d787ca80-b5ed-11e7-95cf-be44e81b842e.png)

**Comment by Dominus77** [comment]
Model SendtextForm
```
namespace modules\sms\models;
use modules\sms\Module;

//...
public function attributeLabels()
{
    return [
        'cellPhoneNo' => Module::t('module', 'cellPhoneNo'), // This lang file in: /modules/sms/messages/zh-TW/module.php
        'message' => Yii::t('app', 'Message'), // This lang file in: /frontend/messages/zh-TW/app.php
    ];
}
//...
```

**Comment by polinwei** [comment]
Yes , I also did it. It can not show the message: zh-TW\module.php

![sendtextform](https://user-images.githubusercontent.com/7941129/31830789-deadc9ee-b5f3-11e7-9503-de5c4619e9c7.png)

**Comment by polinwei** [comment]
Hi Sir:
I found out the key point . The key word is sensitive. I correct it then can work.

**Comment by Dominus77** [comment]
Yes, it should be 1 in 1

**Comment by Dominus77** [comment]
/modules/sms/messages/zh-TW/module.php
```
return [
    //...
    'cellPhoneNo' => 'This cellPhoneNo',
    //...
];
```

**Comment by polinwei** [comment]
thanks a lot.
