### ISSUE TITLE
Which folder should put the new system?

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#2]
If I want to create a blog system base on your yii2-advanced-start, which models folder should put the new system? common\models or modules\blog\models ?

**Comment by Dominus77** [comment]
If you follow the modular system, then modules / blog.
As an example [https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/main](https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/main)
Modules in common / config are connected [https://github.com/Dominus77/yii2-advanced-start/blob/288682261f87af0a72a6abb2693d55d0076c8fe5/common/config/main.php#L7](https://github.com/Dominus77/yii2-advanced-start/blob/288682261f87af0a72a6abb2693d55d0076c8fe5/common/config/main.php#L7)

**Comment by polinwei** [comment]
Thanks!!
