### ISSUE TITLE
Bootstrap tooltip not work

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#20]
I modify the code `'original-title' => Module::t('module', 'Click to change auth key')` in the view: _profile.php , I follow the index.php to want to show tooltip , but not work. Could you tell me why?

![tooltip](https://user-images.githubusercontent.com/7941129/35028135-6385ccc6-fb8f-11e7-83f9-f116e4baf261.png)

HTML:

```
[
	'attribute' => 'auth_key',
	'format' => 'raw',
	'value' => function($data){
		if ( $data->id == Yii::$app->user->identity->getId()){
			$this->registerJs("$('#gen_auth_key_link_" . $data->id . "').click(handleAjaxLink);", \yii\web\View::POS_READY);
			return Html::label($data->auth_key,'',[
					'id' => 'auth_key_' . $data->id,
					]) .' '.
				Html::a('<span class="label label-warning">Generate</span>' , Url::to(['gen-authkey', 'id' => $data->id]) , [
					'id' => 'gen_auth_key_link_' . $data->id,
					'data' => [
						'pjax' => 0,
						'toggle' => 'tooltip',
						'replace-id' => 'auth_key_' . $data->id,
						'original-title' => Module::t('module', 'Click to change auth key'),
					],
				]);

		}

		return $data->auth_key;
	}

],
```

**Comment by Dominus77** [comment]
Try this:
```
Html::a('<span class="label label-warning">Generate</span>' , Url::to(['gen-authkey', 'id' => $data->id]) , [
    'id' => 'gen_auth_key_link_' . $data->id,
    'title' => Module::t('module', 'Click to change auth key'),
    'data' => [
        'pjax' => 0
        'toggle' => 'tooltip',
        'replace-id' => 'auth_key_' . $data->id,
    ]
]);
```
or register the tooltip on the data-original-title:
https://github.com/Dominus77/yii2-advanced-start/blob/4d09e4b3d92e02edf8a92ed81e46e9f9ca0ed205/backend/web/js/dashboard.js#L10

**Comment by polinwei** [comment]
The method: `yii2-advanced-start/backend/web/js/dashboard.js` does not work.

`$('[data-toggle="tooltip"]').tooltip(); `

**Comment by Dominus77** [comment]
Create a test link
https://github.com/Dominus77/yii2-advanced-start/blob/a15144514de7064e8e996a2b0234bbf91bfc26eb/modules/main/views/frontend/default/index.php#L19

![2018-01-18_115133](https://user-images.githubusercontent.com/9594483/35088818-fe621860-fc45-11e7-998f-7c71f7506d5f.png)

To support the tooltip in the frontend do the following:

1. Create js file: `/frontend/web/js/my_script.js`
```
/**
 * My scripts
 */
$(function () {
    $('[data-toggle="tooltip"]').tooltip();
});
```
2. Connect it to AppAsset.php
https://github.com/Dominus77/yii2-advanced-start/blob/a15144514de7064e8e996a2b0234bbf91bfc26eb/frontend/assets/AppAsset.php#L33-L35

We check:

![2018-01-18_115238](https://user-images.githubusercontent.com/9594483/35088858-226e0444-fc46-11e7-8f96-b3b30a957f81.png)

Done!

**Comment by Dominus77** [comment]
Another way to register the script in the current form:
View:
```
<?php
/* @var $this yii\web\View */
$this->registerJs("
    $(function () {
        $('[data-toggle=\"tooltip\"]').tooltip();
    });
");
?>
<a href="#" data-toggle="tooltip" title="This title tooltip">Link</a> 
```
or
```
<?php
/* @var $this yii\web\View */
$this->registerJs(new \yii\web\JsExpression("
    $(function () {
        $('[data-toggle=\"tooltip\"]').tooltip();
    });
"), yii\web\View::POS_END);
?>
<a href="#" data-toggle="tooltip" title="This title tooltip">Link</a>
```
Done!
