### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mohananton** [Dominus77/yii2-advanced-start#22]
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at wampserver@wampserver.invalid to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.23 (Win64) PHP/5.6.25 Server at localhost Port 80

I am using wamp, I have configure .htaccess file in www folder.

can you pls help me on this.

**Comment by Dominus77** [comment]
Hi!
At the root of the project there is a file [requirements.php](https://github.com/Dominus77/yii2-advanced-start/blob/master/requirements.php). Run it on your server from the frontend/web folder. This will check the requirements for correct operation of yii.

**Comment by mohananton** [comment]
Thanks a lot I found the error.
Excellent work by the way..
Your template help us a lot..

**Comment by Dominus77** [comment]
Very nice)
