### ISSUE TITLE
Installation requirement php ^7.0

### ISSUE THREAD

**Issue by neuronet77** [Dominus77/yii2-advanced-start#24]
You are stating requirement is php 5.6 but...

  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 2
    - Installation request for myclabs/deep-copy 1.8.1 -> satisfiable by myclabs/deep-copy[1.8.1].
    - myclabs/deep-copy 1.8.1 requires php ^7.1 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 3
    - Installation request for phpdocumentor/reflection-docblock 4.3.0 -> satisfiable by phpdocumentor/reflection-docblock[4.3.0].
    - phpdocumentor/reflection-docblock 4.3.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 4
    - Installation request for phpunit/php-code-coverage 5.3.2 -> satisfiable by phpunit/php-code-coverage[5.3.2].
    - phpunit/php-code-coverage 5.3.2 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 5
    - Installation request for phpunit/php-token-stream 2.0.2 -> satisfiable by phpunit/php-token-stream[2.0.2].
    - phpunit/php-token-stream 2.0.2 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 6
    - Installation request for phpunit/phpunit 6.5.9 -> satisfiable by phpunit/phpunit[6.5.9].
    - phpunit/phpunit 6.5.9 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 7
    - Installation request for phpunit/phpunit-mock-objects 5.0.8 -> satisfiable by phpunit/phpunit-mock-objects[5.0.8].
    - phpunit/phpunit-mock-objects 5.0.8 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 8
    - Installation request for sebastian/comparator 2.1.3 -> satisfiable by sebastian/comparator[2.1.3].
    - sebastian/comparator 2.1.3 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 9
    - Installation request for sebastian/diff 2.0.1 -> satisfiable by sebastian/diff[2.0.1].
    - sebastian/diff 2.0.1 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 10
    - Installation request for sebastian/environment 3.1.0 -> satisfiable by sebastian/environment[3.1.0].
    - sebastian/environment 3.1.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 11
    - Installation request for sebastian/exporter 3.1.0 -> satisfiable by sebastian/exporter[3.1.0].
    - sebastian/exporter 3.1.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 12
    - Installation request for sebastian/global-state 2.0.0 -> satisfiable by sebastian/global-state[2.0.0].
    - sebastian/global-state 2.0.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 13
    - Installation request for sebastian/object-enumerator 3.0.3 -> satisfiable by sebastian/object-enumerator[3.0.3].
    - sebastian/object-enumerator 3.0.3 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 14
    - Installation request for sebastian/object-reflector 1.1.1 -> satisfiable by sebastian/object-reflector[1.1.1].
    - sebastian/object-reflector 1.1.1 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 15
    - Installation request for sebastian/recursion-context 3.0.0 -> satisfiable by sebastian/recursion-context[3.0.0].
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 16
    - Installation request for symfony/browser-kit v4.1.3 -> satisfiable by symfony/browser-kit[v4.1.3].
    - symfony/browser-kit v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 17
    - Installation request for symfony/console v4.1.3 -> satisfiable by symfony/console[v4.1.3].
    - symfony/console v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 18
    - Installation request for symfony/css-selector v4.1.3 -> satisfiable by symfony/css-selector[v4.1.3].
    - symfony/css-selector v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 19
    - Installation request for symfony/dom-crawler v4.1.3 -> satisfiable by symfony/dom-crawler[v4.1.3].
    - symfony/dom-crawler v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 20
    - Installation request for symfony/event-dispatcher v4.1.3 -> satisfiable by symfony/event-dispatcher[v4.1.3].
    - symfony/event-dispatcher v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 21
    - Installation request for symfony/finder v4.1.3 -> satisfiable by symfony/finder[v4.1.3].
    - symfony/finder v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 22
    - Installation request for symfony/yaml v4.1.3 -> satisfiable by symfony/yaml[v4.1.3].
    - symfony/yaml v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 23
    - Installation request for theseer/tokenizer 1.1.0 -> satisfiable by theseer/tokenizer[1.1.0].
    - theseer/tokenizer 1.1.0 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
  Problem 24
    - phpunit/php-code-coverage 5.3.2 requires php ^7.0 -> your PHP version (5.6.37) does not satisfy that requirement.
    - codeception/base 2.3.9 requires phpunit/php-code-coverage >=2.2.4 <6.0 -> satisfiable by phpunit/php-code-coverage[5.3.2].
    - Installation request for codeception/base 2.3.9 -> satisfiable by codeception/base[2.3.9].

**Comment by Dominus77** [comment]
Yes, support PHP: 5.5, 5.6, 7, 7.1, 7.2
Installation process with tests: https://travis-ci.org/Dominus77/yii2-advanced-start/builds/411120107

**Comment by Dominus77** [comment]
Yes, support PHP Versions: 5.5, 5.6, 7, 7.1, 7.2
View installation process and tests: https://travis-ci.org/Dominus77/yii2-advanced-start/builds/411120107

Please Installation:
```
composer self-update
composer create-project --prefer-dist --stability=dev dominus77/yii2-advanced-start advanced-project
```
See more: https://github.com/Dominus77/yii2-advanced-start#installation
