### ISSUE TITLE
discovering url

### ISSUE THREAD

**Issue by erwinsaid** [Dominus77/yii2-advanced-start#25]
install this template on my localhost following the instructions of https://dominus77.github.io/yii2-advanced-start/ and there was no problem, what I'm missing is to start the system since I do not know what to put, provide with http : //127.0.0.1/admin/user/login and answer me error 404 provide other urls with the same result, could you help me in this, thanks and apologies for my english I am using translator

**Comment by Dominus77** [comment]
Hello, please install according to this instruction: https://github.com/Dominus77/yii2-advanced-start#installation
 Access to admin panel `http://sitename.com/admin`

**Comment by Dominus77** [comment]
The routing rules for the users module are installed in the Bootstrap.php file: https://github.com/Dominus77/yii2-advanced-start/blob/f22f0adce29f7b29765d48317cc3c7509c5ad26f/modules/users/Bootstrap.php#L48

**Comment by erwinsaid** [comment]
I followed the indications of https://github.com/Dominus77/yii2-advanced-start#installation and the whole installation worked according to the indications, but when I wanted to start with the url http://127.0.0.1/admin/ it shows me the error 404, my local server is installed in ubuntu 16.04.

**Comment by Dominus77** [comment]
`http://127.0.0.1` Does the site work?
If you work with Apache, are there files .htaccess?
Check if the mod_rewrite module is enabled on the server.

**Comment by Dominus77** [comment]
https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04

**Comment by erwinsaid** [comment]
Solved and thanks for your help, regards
