### ISSUE TITLE
routes

### ISSUE THREAD

**Issue by erwinsaid** [Dominus77/yii2-advanced-start#26]
How do I create a new permission and relate it to my action (backend / modules / company / create) ?, this because in the action create Permission, it does not show me the routes of the actions to relate it.

**Comment by Dominus77** [comment]
You can create a rule in the web interface or add it to the RBAC initialization, then put a check in the controller. Recorded a video on creating RBAC rules, binding to roles, and access checks.

https://yadi.sk/i/5GSs2sIky-d4Nw

**Comment by erwinsaid** [comment]
Thank you
