### ISSUE TITLE
Translate the menu

### ISSUE THREAD

**Issue by SwapnilAkolkar** [Dominus77/yii2-advanced-start#28]
Hi it is in Russian language how can I change its language

**Comment by Dominus77** [comment]
Hi, the language changes in the application configuration files:
frontend:
https://github.com/Dominus77/yii2-advanced-start/blob/de43ce424ab38ef23bd6bcd95ddee5a3c4a35afd/frontend/config/main.php#L38
backend:
https://github.com/Dominus77/yii2-advanced-start/blob/de43ce424ab38ef23bd6bcd95ddee5a3c4a35afd/backend/config/main.php#L11

**Comment by SwapnilAkolkar** [comment]
I want to install it on localhost , the project works fine onle server but not on windows as it is under advanced_project folder . I am not able to edit the given .htaccess to work with localhost. can you have any suggestions ? I tried to add advanced_project folder in path befor frontend and backend entries in original htaccess.

**Comment by Dominus77** [comment]
The entire project is uploaded to a folder accessible from the Internet, public_html. Files .htaccess are already configured to work correctly. In most cases, they do not change.

Or what exactly you can not?

**Comment by SwapnilAkolkar** [comment]
my htaccess is here
c:/xampp/htdocs/advanced-project/.htaccess
And thats why I am not able to run it on localhost

**Comment by SwapnilAkolkar** [comment]
It works perfectly on server in public_html but I want to edit and customize it on localhost , but the front page not showing

**Comment by SwapnilAkolkar** [comment]
what I tried is
Options FollowSymLinks
AddDefaultCharset utf-8

<IfModule mod_rewrite.c>
    RewriteEngine On

    # the main rewrite rule for the frontend application
    RewriteCond %{REQUEST_URI} !^/(backend/web|admin)
    RewriteCond %{REQUEST_URI} !^/(api/web|api)
    RewriteRule !^advanced-project/frontend/web /advanced-project/frontend/web%{REQUEST_URI} [L]

    # redirect to the page without a trailing slash (uncomment if necessary)
    #RewriteCond %{REQUEST_URI} ^/admin/$
    #RewriteRule ^(admin)/ /$1 [L,R=301]
    # the main rewrite rule for the backend application
    RewriteCond %{REQUEST_URI} ^/admin
    RewriteRule ^admin(.*) /advanced-project/backend/web/$1 [L]

    # redirect to the page without a trailing slash (uncomment if necessary)
    #RewriteCond %{REQUEST_URI} ^/api/$
    #RewriteRule ^(api)/ /$1 [L,R=301]
    # the main rewrite rule for the api application
    RewriteCond %{REQUEST_URI} ^/api
    RewriteRule ^api(.*) /api/web/$1 [L]

    # if a directory or a file of the frontend application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/advanced-project/frontend/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /advanced-project/frontend/web/index.php [L]

    # if a directory or a file of the backend application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/advanced-project/backend/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /advanced-project/backend/web/index.php [L]

    # if a directory or a file of the api application exists, use the request directly
    RewriteCond %{REQUEST_URI} ^/api/web
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # otherwise forward the request to index.php
    RewriteRule . /api/web/index.php [L]

    RewriteCond %{REQUEST_URI} \.(htaccess|htpasswd|svn|git)
    RewriteRule \.(htaccess|htpasswd|svn|git) - [F]
</IfModule>
But not works..

**Comment by SwapnilAkolkar** [comment]
sorry I am not gettig how to configure it for localhost . if project is under /advanced-project/ in htdocs

**Comment by SwapnilAkolkar** [comment]
HI got some success with this htaccess but only problem is js and css are not loading correctly..

**Comment by Dominus77** [comment]
Most likely the server settings. Apache should look at the root of the project in the directory c:/xampp/htdocs/advanced-project

Also check if there is .htaccess in the directory c:/xampp/htdocs/advanced-project/frontend/web and c:/xampp/htdocs/advanced-project/backend/web

**Comment by Dominus77** [comment]
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.php

**Comment by Dominus77** [comment]
Check Apache mod_rewrite

**Comment by SwapnilAkolkar** [comment]
thanks by default the xampp root is c:\xampp\htdocs 
and my current output is
![image](https://user-images.githubusercontent.com/16646010/55294358-d02ef080-541e-11e9-8846-b14ec01b7b9e.png)
for front end and it shows links to about as localhost/about instead of localhost/advanced-project/about

**Comment by SwapnilAkolkar** [comment]
does I need to change here
return [
    'id' => 'app-frontend',
    'language' => 'en',
    'homeUrl' => '/',
    'basePath' => dirname(__DIR__),
    'bootstrap' => [
        'log',
        'modules\main\Bootstrap',
        'modules\users\Bootstrap',
        'modules\rbac\Bootstrap',
    ],

**Comment by Dominus77** [comment]
no

**Comment by Dominus77** [comment]
You need to configure the server to the root directory of the project.

**Comment by SwapnilAkolkar** [comment]
ok thanks for suggestions..

**Comment by Dominus77** [comment]
Try to log in: http://localhost/advanced-project/frontend/web
