### ISSUE TITLE
Admin tables pagination not working

### ISSUE THREAD

**Issue by jcenrique** [Dominus77/yii2-advanced-start#29]
Permissions and users tables pagination not show

**Comment by jcenrique** [comment]
With 17 records and pagination 10
![Captura](https://user-images.githubusercontent.com/16383217/75913618-8f700080-5e53-11ea-8b9e-e7e452dc2bba.PNG)

**Comment by Dominus77** [comment]
Thanks, missing LinkPager widget.

fix: https://github.com/Dominus77/yii2-advanced-start/commit/bd889527098dbec122aab931999444333f81c9db

![Снимок экрана от 2020-03-04 22-50-53](https://user-images.githubusercontent.com/9594483/75917842-b63a3100-5e6b-11ea-86f3-f8c360db9208.png)

![Снимок экрана от 2020-03-04 22-50-21](https://user-images.githubusercontent.com/9594483/75917852-bcc8a880-5e6b-11ea-91c1-ede3e186d878.png)

![Снимок экрана от 2020-03-04 22-50-37](https://user-images.githubusercontent.com/9594483/75917863-c225f300-5e6b-11ea-8727-194f880a2586.png)

**Comment by jcenrique** [comment]
Thanks, un gran trabajo
