### ISSUE TITLE
rbac

### ISSUE THREAD

**Issue by frendays** [Dominus77/yii2-advanced-start#30]
У меня роль super_admin не могу получить к админу почему ?

use modules\rbac\models\Role;
if (Yii::$app->can(Role::ROLE_ADMIN)) {

}

получаю если явно задать 
use modules\rbac\models\Role;
if (Yii::$app->can(Role::ROLE_SUPER_ADMIN)) {

} 

но super_admin в иерархии выше чем одмин ?
![изображение](https://user-images.githubusercontent.com/14954461/76938780-49fa0b80-6908-11ea-8498-994153541cf7.png)

**Comment by Dominus77** [comment]
Роль привязана к пользователю?

**Comment by frendays** [comment]
![изображение](https://user-images.githubusercontent.com/14954461/76939420-677ba500-6909-11ea-9d1c-dbbb231381fa.png)
да

**Comment by Dominus77** [comment]
RBAC строится на основе разрешений, к каждой роли добавляются разрешения, то есть роль это группа разрешений. И у вас синтаксическая ошибка Yii::$app->->can

**Comment by Dominus77** [comment]
![Снимок экрана от 2020-03-18 11-32-32](https://user-images.githubusercontent.com/9594483/76941059-64ce7f00-690c-11ea-9723-521ce6724852.png)

**Comment by frendays** [comment]
синтаксическая ошибка случайно в комментарии допустил в коде норм ! Вы хотите сказать нельзя проверить роль admin ?

**Comment by Dominus77** [comment]
Почему же нельзя, проверить можно все и роли и разрешения

**Comment by frendays** [comment]
Ну я хочу проверить если админ дать доступ ! если super_admin то он тоже должен получить доступ т.к. он выше в иерархии . p.s ,tp разрешений (Permission)
Как это сделать ? 
if (Yii::$app->authManager->checkAccess(Yii::$app->user->id, Role::ROLE_ADMIN)) {
||
if (Yii::$app->user->can(Role::ROLE_ADMIN)) {

**Comment by Dominus77** [comment]
![Снимок экрана от 2020-03-18 11-45-15](https://user-images.githubusercontent.com/9594483/76941976-04404180-690e-11ea-8fcb-ff93035692a2.png)
![Снимок экрана от 2020-03-18 11-45-30](https://user-images.githubusercontent.com/9594483/76941996-0b674f80-690e-11ea-9e6f-a020ad8d3076.png)

**Comment by Dominus77** [comment]
аналогично проверка остальных ролей и разрешений

**Comment by Dominus77** [comment]
if(Yii::$app->user->can(modules\rbac\models\Role::ROLE_SUPER_ADMIN) || Yii::$app->user->can(modules\rbac\models\Role::ROLE_ADMIN)) {
    echo 'Доступ разрешен';
}

**Comment by Dominus77** [comment]
`if(Yii::$app->user->can(modules\rbac\models\Role::ROLE_SUPER_ADMIN) || Yii::$app->user->can(modules\rbac\models\Role::ROLE_ADMIN)) {
    echo 'Доступ разрешен';
}`

**Comment by frendays** [comment]
у меня с разрешением началась проблема потом я к роли перешел ! роль можно опустить ! но вот с разрешение беда не пойму в AuthorRule.php возвращаю всегда true он  не проверяет условие проект ваш давно скачивал но всё работало вроде перешел на новое php7.4.4 mysql 8 но может не из этого проблема пример ниже

use modules\rbac\models\Permission;
use modules\rbac\models\Role;
Yii::$app->authManager->invalidateCache();

$var = Yii::$app->authManager->getRolesByUser(Yii::$app->user->id);
echo "<pre>";
print_r($var);
echo "</pre>";
if(Yii::$app->user->can('super_admin')){
    echo 'super_admin ok <br/>';
}else{
    echo 'super_admin no <br/>';
}

//здесь проблема
if(Yii::$app->user->can(Permission::PERMISSION_UPDATE_OWN_POST, ['post' => $profile])){
    echo 'PERMISSION_UPDATE_OWN_POST ok <br/>';
}else{
    echo 'PERMISSION_UPDATE_OWN_POST no <br/>';
}


### **_`

> \modules\rbac\components\AuthorRule.php

`_**

class AuthorRule extends Rule
{
    public $name = 'isAuthor';

    public function execute($user, $item, $params)
    {
    
        return true; // для теста 1 тоже пробовал...

    }
}


![изображение](https://user-images.githubusercontent.com/14954461/76944163-91d16080-6911-11ea-866e-f80a2181ea4d.png)

**Comment by Dominus77** [comment]
Кажется я понял что вам нужно. Вам нужно что бы роли наследовались? 
https://github.com/Dominus77/yii2-advanced-start/blob/61c3093499328a132afe27aa5434db144c917cb6/modules/rbac/console/InitController.php#L54
Для этих целей вам надо раскомментировать данную строку и выполнить повторную инициализацию RBAC

`php yii rbac/init`

В текущем варианте, роли не наследуются, им присваиваются только разрешения и чем выше роль тем больше разрешений, то есть супер администратор, получает все разрешения.

![Снимок экрана от 2020-03-19 08-01-17](https://user-images.githubusercontent.com/9594483/77033381-2393a900-69b8-11ea-9c9f-a7ae500b4fb7.png)

При выполнении выше рекомендаций, мы получаем следующую структуру наследования ролей

![Снимок экрана от 2020-03-19 08-04-47](https://user-images.githubusercontent.com/9594483/77033474-59d12880-69b8-11ea-93e5-9e101e3615fe.png)

**Comment by frendays** [comment]
Да всё верно !
