### ISSUE TITLE
Do we have an example nginx config somewhere? 

### ISSUE THREAD

**Issue by drew1two** [Dominus77/yii2-advanced-start#35]
Just wondering if someone has a nginx config example... I having a little trouble.
Thanx in advance.

**Comment by Dominus77** [comment]
[yii2-app-advanced on single domain (Apache, Nginx)](https://www.yiiframework.com/wiki/799/yii2-app-advanced-on-single-domain-apache-nginx)

**Comment by drew1two** [comment]
Haha  thank you :)  I'd been using my own doctered config for so long now ... lol Back to original and all is well :)
Thanks again.
