### ISSUE TITLE
Role Based Access Control Asign for create new user in backend UI

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-advanced-start#9]
May you add the create new user in backend UI: Role Based Access Control Asign ?

**Comment by Dominus77** [comment]
Yes, and what is the problem?

**Comment by Dominus77** [comment]
In the latter, the web interface RBAC
[https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/rbac](https://github.com/Dominus77/yii2-advanced-start/tree/master/modules/rbac)

**Comment by polinwei** [comment]
Assign rights does not have the `create action`

**Comment by Dominus77** [comment]
The binding of the role to the user occurs here:
[https://github.com/Dominus77/yii2-advanced-start/blob/3a9e5ac0b5d0b527aa3f2ecb7ea77f84419fd0cd/modules/rbac/controllers/backend/AssignController.php#L95](https://github.com/Dominus77/yii2-advanced-start/blob/3a9e5ac0b5d0b527aa3f2ecb7ea77f84419fd0cd/modules/rbac/controllers/backend/AssignController.php#L95)

**Comment by Dominus77** [comment]
Download my latest version, there are bugs fixed and there are additions and improvements

**Comment by Dominus77** [comment]
New roles are created here:
[https://github.com/Dominus77/yii2-advanced-start/blob/3a9e5ac0b5d0b527aa3f2ecb7ea77f84419fd0cd/modules/rbac/controllers/backend/RolesController.php#L88](https://github.com/Dominus77/yii2-advanced-start/blob/3a9e5ac0b5d0b527aa3f2ecb7ea77f84419fd0cd/modules/rbac/controllers/backend/RolesController.php#L88)

**Comment by polinwei** [comment]
May I using `composer update Dominus77/yii2-advanced-start` ?

**Comment by Dominus77** [comment]
Try it, but it's better to put it again.
As it is written in README.md
```
composer global require "fxp/composer-asset-plugin:^1.2.0"
composer create-project --prefer-dist --stability=dev dominus77/yii2-advanced-start advanced-project
```
Then move your files to a new project, the structure and the principle remained

**Comment by polinwei** [comment]
Do you plan save the Layout Options status in session or table?

**Comment by Dominus77** [comment]
what do you mean?

**Comment by polinwei** [comment]
When I refresh backend page , The AdminLTE layout back to normal.

**Comment by Dominus77** [comment]
I do not plan yet, but you can implement this functionality yourself)

**Comment by polinwei** [comment]
Ok. thanks!!
